#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx commitlint --edit $1 || (echo "⛔ Commit Message ไม่ผ่าน กิตต้นไม่ให้ Commit งับ" && exit 1)

echo "✅ Commit Message ผ่าน กิตต้นให้ Commit ได้ เก่งมากๆ"
