#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm run format || (echo "⛔ Format Failed" && exit 1)
pnpm run lint || (echo "⛔ Lint Failed" && exit 1)
pnpm run build || (echo "⛔ Build Failed" && exit 1)

git add .

echo "✅ Format, Lint, Build Passed"
  