name: Deploy to Self-Hosted

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Clear Cache
        run: |
          docker stop ceboostupxi-dashboard || true
          docker rm ceboostupxi-dashboard || true
          docker rmi ceboostupxi-dashboard:latest || true
      - name: Build Image
        run: |
          docker build --no-cache . \
            --file Dockerfile \
            --tag ceboostupxi-dashboard
      - name: Run Image
        run: |
          docker run --restart always -d \
            -e PORT=${{ secrets.PORT }} \
            -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            --network reverse-proxy_default \
            --name ceboostupxi-dashboard \
            ceboostupxi-dashboard:latest
